### ISSUE TITLE
[bug] words with multiple letters are not taken into account correctly

### ISSUE THREAD

**Issue by hwmrocker** [pythonfoo/rest-wordle#1]
e.g the secret word is `world` and the guessed word is `stall` we would get
:black_circle: :black_circle: :black_circle: :green_circle: :yellow_circle:

the second l should be black since we have only one l in the secret word.

**Comment by wilsonfontein** [comment]
I have an idea how to solve it. I will create an PR later today.

**Comment by hwmrocker** [comment]
Cool, looking forward to the PR :)
